import type { Metadata } from "next";
import { Inter, Noto_Sans_JP, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/style";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const notoSansJP = Noto_Sans_JP({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
  title: "White Mouse Japanese",
  description: "Generated by Kun Woo Kim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.variable, notoSansJP.variable)}>
        {children}
      </body>
    </html>
  );
}
